version: '2.1'

services:
  myqrcode:
    image: myqrcode
    build: .
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
    environment: 
      - http_proxy=${http_proxy}
      - https_proxy=${https_proxy}